tablet version 0.1
kenzaofficial/pink pull request #1
Opened 2022-01-16 18:16 UTC by kenzaofficial

2022-03-26 07:55 UTC, baronin commented
Сделай все как по дизайну и продолжим

2022-03-26 07:55 UTC, baronin requested changes
Начало хорошее) Работаем

2022-03-26 22:00 UTC, kenzaofficial commented
> 

есть

2022-03-27 18:40 UTC, baronin requested changes
Поправь что обсудили, а так супер

2022-03-29 12:53 UTC, baronin approved these changes
Видно что стараешься, так держать !

2022-03-29 13:02 UTC, merged